service: madrid-traffic-connector

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

package:
  exclude:
   - config.env

functions:
  incidences:
    handler: handler.incidences
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(2 minutes)
    timeout: 60

  servicelevel:
    handler: handler.servicelevel
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(5 minutes)
    timeout: 120

  intensitypois:
    handler: handler.intensitypois
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(5 minutes)
    timeout: 120

  intensitylines:
    handler: handler.intensitylines
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(5 minutes)
    timeout: 120

  trafficlightsacustw:
    handler: handler.trafficlightsacustw
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(15 days)
    timeout: 180

  trafficlightsred:
    handler: handler.trafficlightsred
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(15 days)
    timeout: 180

  cameras:
    handler: handler.cameras
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(2 hours)
    timeout: 180

  streetsgeocoder:
    handler: handler.streetsgeocoder
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
      WAZE_GEOCODER_TOKEN: ${env:WAZE_GEOCODER_TOKEN}
    events:
      - schedule: rate(5 minutes)
    timeout: 200

  pollutionIncidences:
    handler: handler.pollutionIncidences
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(2 minutes)
    timeout: 60

  pollutionScenarios:
    handler: handler.pollutionScenarios
    environment:
      # CARTO_USERNAME: ${env:CARTO_USERNAME}
      # CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(2 minutes)
    timeout: 60
