service: madrid-traffic-connector

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  incidences:
    handler: handler.incidences
    environment:
      CARTO_USERNAME: waze-traffic
      CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(2 minutes)
    timeout: 60

  servicelevel:
    handler: handler.servicelevel
    environment:
      CARTO_USERNAME: waze-traffic
      CARTO_API_KEY: ${env:CARTO_API_KEY}
    events:
      - schedule: rate(5 minutes)
    timeout: 120
